[package]
name = "provlita"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.1"
description = "A native Sophia GPU dock inspired by Gershwin"
license = "BSD-3-Clause"
repository = "https://github.com/sophia-org/provlita"
publish = false

[lints.rust]
missing_docs = "warn"

[dependencies]
sophia-shell-protocol = { git = "https://github.com/sophia-org/sophia-desktop-sdk-rs", rev = "ea9cf651d37649fc1be889b3cfef6c1729b055f8" }
sophia-shell-client = { git = "https://github.com/sophia-org/sophia-desktop-sdk-rs", rev = "ea9cf651d37649fc1be889b3cfef6c1729b055f8" }
sophia-shell-gpu = { git = "https://github.com/sophia-org/lom", rev = "ad349869a8ce3f9eff77c6b91465b80cb54198b6" }
kdl = { version = "=6.7.1", default-features = false, features = ["span"] }
xilem_masonry = { git = "https://github.com/linebender/xilem", rev = "b81d8d7a631849def6eeab282561439b963862e5", default-features = false }
masonry = { git = "https://github.com/linebender/xilem", rev = "b81d8d7a631849def6eeab282561439b963862e5", default-features = false }
libc = "0.2"
tokio = { version = "1.50", features = ["rt", "sync"] }

[dev-dependencies]
wgpu = { version = "28.0", default-features = false }
imaging_vello_cpu = "0.0.1"
masonry_testing = { git = "https://github.com/linebender/xilem", rev = "b81d8d7a631849def6eeab282561439b963862e5", default-features = false }
