[package]
name = "provlita"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.1"
description = "A native Sophia GPU dock inspired by Gershwin"
license = "BSD-3-Clause"
repository = "https://github.com/sophia-org/provlita"
publish = false

[lints.rust]
missing_docs = "warn"

[dependencies]
kdl = { version = "=6.7.1", default-features = false, features = ["span"] }
